
export const timezones = [{ label: "UTC - 11:00 - United States Minor Outlying Islands , Midway" , value: "UTC - 11:00 - United States Minor Outlying Islands , Midway" },
{ label: "UTC - 11:00 - Niue , Niue" , value: "UTC - 11:00 - Niue , Niue" },
{ label: "UTC - 11:00 - American Samoa , Pago_Pago" , value: "UTC - 11:00 - American Samoa , Pago_Pago" },
{ label: "UTC - 10:00 - United States , Adak" , value: "UTC - 10:00 - United States , Adak" },
{ label: "UTC - 10:00 - United States , Honolulu" , value: "UTC - 10:00 - United States , Honolulu" },
{ label: "UTC - 10:00 - Cook Islands , Rarotonga" , value: "UTC - 10:00 - Cook Islands , Rarotonga" },
{ label: "UTC - 10:00 - French Polynesia , Tahiti" , value: "UTC - 10:00 - French Polynesia , Tahiti" },
{ label: "UTC - 09:30 - French Polynesia , Marquesas" , value: "UTC - 09:30 - French Polynesia , Marquesas" },
{ label: "UTC - 09:00 - United States , Anchorage" , value: "UTC - 09:00 - United States , Anchorage" },
{ label: "UTC - 09:00 - United States , Juneau" , value: "UTC - 09:00 - United States , Juneau" },
{ label: "UTC - 09:00 - United States , Metlakatla" , value: "UTC - 09:00 - United States , Metlakatla" },
{ label: "UTC - 09:00 - United States , Nome" , value: "UTC - 09:00 - United States , Nome" },
{ label: "UTC - 09:00 - United States , Sitka" , value: "UTC - 09:00 - United States , Sitka" },
{ label: "UTC - 09:00 - United States , Yakutat" , value: "UTC - 09:00 - United States , Yakutat" },
{ label: "UTC - 09:00 - French Polynesia , Gambier" , value: "UTC - 09:00 - French Polynesia , Gambier" },
{ label: "UTC - 08:00 - Canada , Dawson" , value: "UTC - 08:00 - Canada , Dawson" },
{ label: "UTC - 08:00 - United States , Los_Angeles" , value: "UTC - 08:00 - United States , Los_Angeles" },
{ label: "UTC - 08:00 - Mexico , Tijuana" , value: "UTC - 08:00 - Mexico , Tijuana" },
{ label: "UTC - 08:00 - Canada , Vancouver" , value: "UTC - 08:00 - Canada , Vancouver" },
{ label: "UTC - 08:00 - Canada , Whitehorse" , value: "UTC - 08:00 - Canada , Whitehorse" },
{ label: "UTC - 08:00 - Pitcairn , Pitcairn" , value: "UTC - 08:00 - Pitcairn , Pitcairn" },
{ label: "UTC - 07:00 - United States , Boise" , value: "UTC - 07:00 - United States , Boise" },
{ label: "UTC - 07:00 - Canada , Cambridge_Bay" , value: "UTC - 07:00 - Canada , Cambridge_Bay" },
{ label: "UTC - 07:00 - Mexico , Chihuahua" , value: "UTC - 07:00 - Mexico , Chihuahua" },
{ label: "UTC - 07:00 - Canada , Creston" , value: "UTC - 07:00 - Canada , Creston" },
{ label: "UTC - 07:00 - Canada , Dawson_Creek" , value: "UTC - 07:00 - Canada , Dawson_Creek" },
{ label: "UTC - 07:00 - United States , Denver" , value: "UTC - 07:00 - United States , Denver" },
{ label: "UTC - 07:00 - Canada , Edmonton" , value: "UTC - 07:00 - Canada , Edmonton" },
{ label: "UTC - 07:00 - Canada , Fort_Nelson" , value: "UTC - 07:00 - Canada , Fort_Nelson" },
{ label: "UTC - 07:00 - Mexico , Hermosillo" , value: "UTC - 07:00 - Mexico , Hermosillo" },
{ label: "UTC - 07:00 - Canada , Inuvik" , value: "UTC - 07:00 - Canada , Inuvik" },
{ label: "UTC - 07:00 - Mexico , Mazatlan" , value: "UTC - 07:00 - Mexico , Mazatlan" },
{ label: "UTC - 07:00 - Mexico , Ojinaga" , value: "UTC - 07:00 - Mexico , Ojinaga" },
{ label: "UTC - 07:00 - United States , Phoenix" , value: "UTC - 07:00 - United States , Phoenix" },
{ label: "UTC - 07:00 - Canada , Yellowknife" , value: "UTC - 07:00 - Canada , Yellowknife" },
{ label: "UTC - 06:00 - Mexico , Bahia_Banderas" , value: "UTC - 06:00 - Mexico , Bahia_Banderas" },
{ label: "UTC - 06:00 - Belize , Belize" , value: "UTC - 06:00 - Belize , Belize" },
{ label: "UTC - 06:00 - United States , Chicago" , value: "UTC - 06:00 - United States , Chicago" },
{ label: "UTC - 06:00 - Costa Rica , Costa_Rica" , value: "UTC - 06:00 - Costa Rica , Costa_Rica" },
{ label: "UTC - 06:00 - El Salvador , El_Salvador" , value: "UTC - 06:00 - El Salvador , El_Salvador" },
{ label: "UTC - 06:00 - Guatemala , Guatemala" , value: "UTC - 06:00 - Guatemala , Guatemala" },
{ label: "UTC - 06:00 - United States , Knox" , value: "UTC - 06:00 - United States , Knox" },
{ label: "UTC - 06:00 - United States , Tell_City" , value: "UTC - 06:00 - United States , Tell_City" },
{ label: "UTC - 06:00 - Nicaragua , Managua" , value: "UTC - 06:00 - Nicaragua , Managua" },
{ label: "UTC - 06:00 - Mexico , Matamoros" , value: "UTC - 06:00 - Mexico , Matamoros" },
{ label: "UTC - 06:00 - United States , Menominee" , value: "UTC - 06:00 - United States , Menominee" },
{ label: "UTC - 06:00 - Mexico , Merida" , value: "UTC - 06:00 - Mexico , Merida" },
{ label: "UTC - 06:00 - Mexico , Mexico_City" , value: "UTC - 06:00 - Mexico , Mexico_City" },
{ label: "UTC - 06:00 - Mexico , Monterrey" , value: "UTC - 06:00 - Mexico , Monterrey" },
{ label: "UTC - 06:00 - United States , Beulah" , value: "UTC - 06:00 - United States , Beulah" },
{ label: "UTC - 06:00 - United States , Center" , value: "UTC - 06:00 - United States , Center" },
{ label: "UTC - 06:00 - United States , New_Salem" , value: "UTC - 06:00 - United States , New_Salem" },
{ label: "UTC - 06:00 - Canada , Rainy_River" , value: "UTC - 06:00 - Canada , Rainy_River" },
{ label: "UTC - 06:00 - Canada , Rankin_Inlet" , value: "UTC - 06:00 - Canada , Rankin_Inlet" },
{ label: "UTC - 06:00 - Canada , Regina" , value: "UTC - 06:00 - Canada , Regina" },
{ label: "UTC - 06:00 - Canada , Resolute" , value: "UTC - 06:00 - Canada , Resolute" },
{ label: "UTC - 06:00 - Canada , Swift_Current" , value: "UTC - 06:00 - Canada , Swift_Current" },
{ label: "UTC - 06:00 - Honduras , Tegucigalpa" , value: "UTC - 06:00 - Honduras , Tegucigalpa" },
{ label: "UTC - 06:00 - Canada , Winnipeg" , value: "UTC - 06:00 - Canada , Winnipeg" },
{ label: "UTC - 06:00 - Chile , Easter" , value: "UTC - 06:00 - Chile , Easter" },
{ label: "UTC - 06:00 - Ecuador , Galapagos" , value: "UTC - 06:00 - Ecuador , Galapagos" },
{ label: "UTC - 05:00 - Canada , Atikokan" , value: "UTC - 05:00 - Canada , Atikokan" },
{ label: "UTC - 05:00 - Colombia , Bogota" , value: "UTC - 05:00 - Colombia , Bogota" },
{ label: "UTC - 05:00 - Mexico , Cancun" , value: "UTC - 05:00 - Mexico , Cancun" },
{ label: "UTC - 05:00 - Cayman Islands , Cayman" , value: "UTC - 05:00 - Cayman Islands , Cayman" },
{ label: "UTC - 05:00 - United States , Detroit" , value: "UTC - 05:00 - United States , Detroit" },
{ label: "UTC - 05:00 - Brazil , Eirunepe" , value: "UTC - 05:00 - Brazil , Eirunepe" },
{ label: "UTC - 05:00 - Turks and Caicos Islands , Grand_Turk" , value: "UTC - 05:00 - Turks and Caicos Islands , Grand_Turk" },
{ label: "UTC - 05:00 - Ecuador , Guayaquil" , value: "UTC - 05:00 - Ecuador , Guayaquil" },
{ label: "UTC - 05:00 - Cuba , Havana" , value: "UTC - 05:00 - Cuba , Havana" },
{ label: "UTC - 05:00 - United States , Indianapolis" , value: "UTC - 05:00 - United States , Indianapolis" },
{ label: "UTC - 05:00 - United States , Marengo" , value: "UTC - 05:00 - United States , Marengo" },
{ label: "UTC - 05:00 - United States , Petersburg" , value: "UTC - 05:00 - United States , Petersburg" },
{ label: "UTC - 05:00 - United States , Vevay" , value: "UTC - 05:00 - United States , Vevay" },
{ label: "UTC - 05:00 - United States , Vincennes" , value: "UTC - 05:00 - United States , Vincennes" },
{ label: "UTC - 05:00 - United States , Winamac" , value: "UTC - 05:00 - United States , Winamac" },
{ label: "UTC - 05:00 - Canada , Iqaluit" , value: "UTC - 05:00 - Canada , Iqaluit" },
{ label: "UTC - 05:00 - Jamaica , Jamaica" , value: "UTC - 05:00 - Jamaica , Jamaica" },
{ label: "UTC - 05:00 - United States , Louisville" , value: "UTC - 05:00 - United States , Louisville" },
{ label: "UTC - 05:00 - United States , Monticello" , value: "UTC - 05:00 - United States , Monticello" },
{ label: "UTC - 05:00 - Peru , Lima" , value: "UTC - 05:00 - Peru , Lima" },
{ label: "UTC - 05:00 - Bahamas , Nassau" , value: "UTC - 05:00 - Bahamas , Nassau" },
{ label: "UTC - 05:00 - United States , New_York" , value: "UTC - 05:00 - United States , New_York" },
{ label: "UTC - 05:00 - Canada , Nipigon" , value: "UTC - 05:00 - Canada , Nipigon" },
{ label: "UTC - 05:00 - Panama , Panama" , value: "UTC - 05:00 - Panama , Panama" },
{ label: "UTC - 05:00 - Canada , Pangnirtung" , value: "UTC - 05:00 - Canada , Pangnirtung" },
{ label: "UTC - 05:00 - Haiti , Port-au-Prince" , value: "UTC - 05:00 - Haiti , Port-au-Prince" },
{ label: "UTC - 05:00 - Brazil , Rio_Branco" , value: "UTC - 05:00 - Brazil , Rio_Branco" },
{ label: "UTC - 05:00 - Canada , Thunder_Bay" , value: "UTC - 05:00 - Canada , Thunder_Bay" },
{ label: "UTC - 05:00 - Canada , Toronto" , value: "UTC - 05:00 - Canada , Toronto" },
{ label: "UTC - 04:00 - Anguilla , Anguilla" , value: "UTC - 04:00 - Anguilla , Anguilla" },
{ label: "UTC - 04:00 - Antigua and Barbuda , Antigua" , value: "UTC - 04:00 - Antigua and Barbuda , Antigua" },
{ label: "UTC - 04:00 - Aruba , Aruba" , value: "UTC - 04:00 - Aruba , Aruba" },
{ label: "UTC - 04:00 - Paraguay , Asuncion" , value: "UTC - 04:00 - Paraguay , Asuncion" },
{ label: "UTC - 04:00 - Barbados , Barbados" , value: "UTC - 04:00 - Barbados , Barbados" },
{ label: "UTC - 04:00 - Canada , Blanc-Sablon" , value: "UTC - 04:00 - Canada , Blanc-Sablon" },
{ label: "UTC - 04:00 - Brazil , Boa_Vista" , value: "UTC - 04:00 - Brazil , Boa_Vista" },
{ label: "UTC - 04:00 - Brazil , Campo_Grande" , value: "UTC - 04:00 - Brazil , Campo_Grande" },
{ label: "UTC - 04:00 - Venezuela , Caracas" , value: "UTC - 04:00 - Venezuela , Caracas" },
{ label: "UTC - 04:00 - Brazil , Cuiaba" , value: "UTC - 04:00 - Brazil , Cuiaba" },
{ label: "UTC - 04:00 - Curacao , Curacao" , value: "UTC - 04:00 - Curacao , Curacao" },
{ label: "UTC - 04:00 - Dominica , Dominica" , value: "UTC - 04:00 - Dominica , Dominica" },
{ label: "UTC - 04:00 - Canada , Glace_Bay" , value: "UTC - 04:00 - Canada , Glace_Bay" },
{ label: "UTC - 04:00 - Canada , Goose_Bay" , value: "UTC - 04:00 - Canada , Goose_Bay" },
{ label: "UTC - 04:00 - Grenada , Grenada" , value: "UTC - 04:00 - Grenada , Grenada" },
{ label: "UTC - 04:00 - Guadeloupe , Guadeloupe" , value: "UTC - 04:00 - Guadeloupe , Guadeloupe" },
{ label: "UTC - 04:00 - Guyana , Guyana" , value: "UTC - 04:00 - Guyana , Guyana" },
{ label: "UTC - 04:00 - Canada , Halifax" , value: "UTC - 04:00 - Canada , Halifax" },
{ label: "UTC - 04:00 - Bonaire, Saint Eustatius and Saba , Kralendijk" , value: "UTC - 04:00 - Bonaire, Saint Eustatius and Saba , Kralendijk" },
{ label: "UTC - 04:00 - Bolivia , La_Paz" , value: "UTC - 04:00 - Bolivia , La_Paz" },
{ label: "UTC - 04:00 - Sint Maarten , Lower_Princes" , value: "UTC - 04:00 - Sint Maarten , Lower_Princes" },
{ label: "UTC - 04:00 - Brazil , Manaus" , value: "UTC - 04:00 - Brazil , Manaus" },
{ label: "UTC - 04:00 - Saint Martin , Marigot" , value: "UTC - 04:00 - Saint Martin , Marigot" },
{ label: "UTC - 04:00 - Martinique , Martinique" , value: "UTC - 04:00 - Martinique , Martinique" },
{ label: "UTC - 04:00 - Canada , Moncton" , value: "UTC - 04:00 - Canada , Moncton" },
{ label: "UTC - 04:00 - Montserrat , Montserrat" , value: "UTC - 04:00 - Montserrat , Montserrat" },
{ label: "UTC - 04:00 - Brazil , Porto_Velho" , value: "UTC - 04:00 - Brazil , Porto_Velho" },
{ label: "UTC - 04:00 - Trinidad and Tobago , Port_of_Spain" , value: "UTC - 04:00 - Trinidad and Tobago , Port_of_Spain" },
{ label: "UTC - 04:00 - Puerto Rico , Puerto_Rico" , value: "UTC - 04:00 - Puerto Rico , Puerto_Rico" },
{ label: "UTC - 04:00 - Chile , Santiago" , value: "UTC - 04:00 - Chile , Santiago" },
{ label: "UTC - 04:00 - Dominican Republic , Santo_Domingo" , value: "UTC - 04:00 - Dominican Republic , Santo_Domingo" },
{ label: "UTC - 04:00 - Saint Barthelemy , St_Barthelemy" , value: "UTC - 04:00 - Saint Barthelemy , St_Barthelemy" },
{ label: "UTC - 04:00 - Saint Kitts and Nevis , St_Kitts" , value: "UTC - 04:00 - Saint Kitts and Nevis , St_Kitts" },
{ label: "UTC - 04:00 - Saint Lucia , St_Lucia" , value: "UTC - 04:00 - Saint Lucia , St_Lucia" },
{ label: "UTC - 04:00 - U.S. Virgin Islands , St_Thomas" , value: "UTC - 04:00 - U.S. Virgin Islands , St_Thomas" },
{ label: "UTC - 04:00 - Saint Vincent and the Grenadines , St_Vincent" , value: "UTC - 04:00 - Saint Vincent and the Grenadines , St_Vincent" },
{ label: "UTC - 04:00 - Greenland , Thule" , value: "UTC - 04:00 - Greenland , Thule" },
{ label: "UTC - 04:00 - British Virgin Islands , Tortola" , value: "UTC - 04:00 - British Virgin Islands , Tortola" },
{ label: "UTC - 04:00 - Bermuda , Bermuda" , value: "UTC - 04:00 - Bermuda , Bermuda" },
{ label: "UTC - 03:30 - Canada , St_Johns" , value: "UTC - 03:30 - Canada , St_Johns" },
{ label: "UTC - 03:00 - Brazil , Araguaina" , value: "UTC - 03:00 - Brazil , Araguaina" },
{ label: "UTC - 03:00 - Argentina , Buenos_Aires" , value: "UTC - 03:00 - Argentina , Buenos_Aires" },
{ label: "UTC - 03:00 - Argentina , Catamarca" , value: "UTC - 03:00 - Argentina , Catamarca" },
{ label: "UTC - 03:00 - Argentina , Cordoba" , value: "UTC - 03:00 - Argentina , Cordoba" },
{ label: "UTC - 03:00 - Argentina , Jujuy" , value: "UTC - 03:00 - Argentina , Jujuy" },
{ label: "UTC - 03:00 - Argentina , La_Rioja" , value: "UTC - 03:00 - Argentina , La_Rioja" },
{ label: "UTC - 03:00 - Argentina , Mendoza" , value: "UTC - 03:00 - Argentina , Mendoza" },
{ label: "UTC - 03:00 - Argentina , Rio_Gallegos" , value: "UTC - 03:00 - Argentina , Rio_Gallegos" },
{ label: "UTC - 03:00 - Argentina , Salta" , value: "UTC - 03:00 - Argentina , Salta" },
{ label: "UTC - 03:00 - Argentina , San_Juan" , value: "UTC - 03:00 - Argentina , San_Juan" },
{ label: "UTC - 03:00 - Argentina , San_Luis" , value: "UTC - 03:00 - Argentina , San_Luis" },
{ label: "UTC - 03:00 - Argentina , Tucuman" , value: "UTC - 03:00 - Argentina , Tucuman" },
{ label: "UTC - 03:00 - Argentina , Ushuaia" , value: "UTC - 03:00 - Argentina , Ushuaia" },
{ label: "UTC - 03:00 - Brazil , Bahia" , value: "UTC - 03:00 - Brazil , Bahia" },
{ label: "UTC - 03:00 - Brazil , Belem" , value: "UTC - 03:00 - Brazil , Belem" },
{ label: "UTC - 03:00 - French Guiana , Cayenne" , value: "UTC - 03:00 - French Guiana , Cayenne" },
{ label: "UTC - 03:00 - Brazil , Fortaleza" , value: "UTC - 03:00 - Brazil , Fortaleza" },
{ label: "UTC - 03:00 - Greenland , Godthab" , value: "UTC - 03:00 - Greenland , Godthab" },
{ label: "UTC - 03:00 - Brazil , Maceio" , value: "UTC - 03:00 - Brazil , Maceio" },
{ label: "UTC - 03:00 - Saint Pierre and Miquelon , Miquelon" , value: "UTC - 03:00 - Saint Pierre and Miquelon , Miquelon" },
{ label: "UTC - 03:00 - Uruguay , Montevideo" , value: "UTC - 03:00 - Uruguay , Montevideo" },
{ label: "UTC - 03:00 - Suriname , Paramaribo" , value: "UTC - 03:00 - Suriname , Paramaribo" },
{ label: "UTC - 03:00 - Chile , Punta_Arenas" , value: "UTC - 03:00 - Chile , Punta_Arenas" },
{ label: "UTC - 03:00 - Brazil , Recife" , value: "UTC - 03:00 - Brazil , Recife" },
{ label: "UTC - 03:00 - Brazil , Santarem" , value: "UTC - 03:00 - Brazil , Santarem" },
{ label: "UTC - 03:00 - Brazil , Sao_Paulo" , value: "UTC - 03:00 - Brazil , Sao_Paulo" },
{ label: "UTC - 03:00 - Antarctica , Palmer" , value: "UTC - 03:00 - Antarctica , Palmer" },
{ label: "UTC - 03:00 - Antarctica , Rothera" , value: "UTC - 03:00 - Antarctica , Rothera" },
{ label: "UTC - 03:00 - Falkland Islands , Stanley" , value: "UTC - 03:00 - Falkland Islands , Stanley" },
{ label: "UTC - 02:00 - Brazil , Noronha" , value: "UTC - 02:00 - Brazil , Noronha" },
{ label: "UTC - 02:00 - South Georgia and the South Sandwich Islands , South_Georgia" , value: "UTC - 02:00 - South Georgia and the South Sandwich Islands , South_Georgia" },
{ label: "UTC - 01:00 - Greenland , Scoresbysund" , value: "UTC - 01:00 - Greenland , Scoresbysund" },
{ label: "UTC - 01:00 - Portugal , Azores" , value: "UTC - 01:00 - Portugal , Azores" },
{ label: "UTC - 01:00 - Cape Verde , Cape_Verde" , value: "UTC - 01:00 - Cape Verde , Cape_Verde" },
{ label: "UTC + 00:00 - Ivory Coast , Abidjan" , value: "UTC + 00:00 - Ivory Coast , Abidjan" },
{ label: "UTC + 00:00 - Ghana , Accra" , value: "UTC + 00:00 - Ghana , Accra" },
{ label: "UTC + 00:00 - Mali , Bamako" , value: "UTC + 00:00 - Mali , Bamako" },
{ label: "UTC + 00:00 - Gambia , Banjul" , value: "UTC + 00:00 - Gambia , Banjul" },
{ label: "UTC + 00:00 - Guinea-Bissau , Bissau" , value: "UTC + 00:00 - Guinea-Bissau , Bissau" },
{ label: "UTC + 00:00 - Guinea , Conakry" , value: "UTC + 00:00 - Guinea , Conakry" },
{ label: "UTC + 00:00 - Senegal , Dakar" , value: "UTC + 00:00 - Senegal , Dakar" },
{ label: "UTC + 00:00 - Sierra Leone , Freetown" , value: "UTC + 00:00 - Sierra Leone , Freetown" },
{ label: "UTC + 00:00 - Togo , Lome" , value: "UTC + 00:00 - Togo , Lome" },
{ label: "UTC + 00:00 - Liberia , Monrovia" , value: "UTC + 00:00 - Liberia , Monrovia" },
{ label: "UTC + 00:00 - Mauritania , Nouakchott" , value: "UTC + 00:00 - Mauritania , Nouakchott" },
{ label: "UTC + 00:00 - Burkina Faso , Ouagadougou" , value: "UTC + 00:00 - Burkina Faso , Ouagadougou" },
{ label: "UTC + 00:00 - Sao Tome and Principe , Sao_Tome" , value: "UTC + 00:00 - Sao Tome and Principe , Sao_Tome" },
{ label: "UTC + 00:00 - Greenland , Danmarkshavn" , value: "UTC + 00:00 - Greenland , Danmarkshavn" },
{ label: "UTC + 00:00 - Antarctica , Troll" , value: "UTC + 00:00 - Antarctica , Troll" },
{ label: "UTC + 00:00 - Spain , Canary" , value: "UTC + 00:00 - Spain , Canary" },
{ label: "UTC + 00:00 - Faroe Islands , Faroe" , value: "UTC + 00:00 - Faroe Islands , Faroe" },
{ label: "UTC + 00:00 - Portugal , Madeira" , value: "UTC + 00:00 - Portugal , Madeira" },
{ label: "UTC + 00:00 - Iceland , Reykjavik" , value: "UTC + 00:00 - Iceland , Reykjavik" },
{ label: "UTC + 00:00 - Saint Helena , St_Helena" , value: "UTC + 00:00 - Saint Helena , St_Helena" },
{ label: "UTC + 00:00 - Guernsey , Guernsey" , value: "UTC + 00:00 - Guernsey , Guernsey" },
{ label: "UTC + 00:00 - Isle of Man , Isle_of_Man" , value: "UTC + 00:00 - Isle of Man , Isle_of_Man" },
{ label: "UTC + 00:00 - Jersey , Jersey" , value: "UTC + 00:00 - Jersey , Jersey" },
{ label: "UTC + 00:00 - Portugal , Lisbon" , value: "UTC + 00:00 - Portugal , Lisbon" },
{ label: "UTC + 00:00 - United Kingdom , London" , value: "UTC + 00:00 - United Kingdom , London" },
{ label: "UTC + 01:00 - Algeria , Algiers" , value: "UTC + 01:00 - Algeria , Algiers" },
{ label: "UTC + 01:00 - Central African Republic , Bangui" , value: "UTC + 01:00 - Central African Republic , Bangui" },
{ label: "UTC + 01:00 - Republic of the Congo , Brazzaville" , value: "UTC + 01:00 - Republic of the Congo , Brazzaville" },
{ label: "UTC + 01:00 - Morocco , Casablanca" , value: "UTC + 01:00 - Morocco , Casablanca" },
{ label: "UTC + 01:00 - Spain , Ceuta" , value: "UTC + 01:00 - Spain , Ceuta" },
{ label: "UTC + 01:00 - Cameroon , Douala" , value: "UTC + 01:00 - Cameroon , Douala" },
{ label: "UTC + 01:00 - Western Sahara , El_Aaiun" , value: "UTC + 01:00 - Western Sahara , El_Aaiun" },
{ label: "UTC + 01:00 - Democratic Republic of the Congo , Kinshasa" , value: "UTC + 01:00 - Democratic Republic of the Congo , Kinshasa" },
{ label: "UTC + 01:00 - Nigeria , Lagos" , value: "UTC + 01:00 - Nigeria , Lagos" },
{ label: "UTC + 01:00 - Gabon , Libreville" , value: "UTC + 01:00 - Gabon , Libreville" },
{ label: "UTC + 01:00 - Angola , Luanda" , value: "UTC + 01:00 - Angola , Luanda" },
{ label: "UTC + 01:00 - Equatorial Guinea , Malabo" , value: "UTC + 01:00 - Equatorial Guinea , Malabo" },
{ label: "UTC + 01:00 - Chad , Ndjamena" , value: "UTC + 01:00 - Chad , Ndjamena" },
{ label: "UTC + 01:00 - Niger , Niamey" , value: "UTC + 01:00 - Niger , Niamey" },
{ label: "UTC + 01:00 - Benin , Porto-Novo" , value: "UTC + 01:00 - Benin , Porto-Novo" },
{ label: "UTC + 01:00 - Tunisia , Tunis" , value: "UTC + 01:00 - Tunisia , Tunis" },
{ label: "UTC + 01:00 - Svalbard and Jan Mayen , Longyearbyen" , value: "UTC + 01:00 - Svalbard and Jan Mayen , Longyearbyen" },
{ label: "UTC + 01:00 - Netherlands , Amsterdam" , value: "UTC + 01:00 - Netherlands , Amsterdam" },
{ label: "UTC + 01:00 - Andorra , Andorra" , value: "UTC + 01:00 - Andorra , Andorra" },
{ label: "UTC + 01:00 - Serbia , Belgrade" , value: "UTC + 01:00 - Serbia , Belgrade" },
{ label: "UTC + 01:00 - Germany , Berlin" , value: "UTC + 01:00 - Germany , Berlin" },
{ label: "UTC + 01:00 - Slovakia , Bratislava" , value: "UTC + 01:00 - Slovakia , Bratislava" },
{ label: "UTC + 01:00 - Belgium , Brussels" , value: "UTC + 01:00 - Belgium , Brussels" },
{ label: "UTC + 01:00 - Hungary , Budapest" , value: "UTC + 01:00 - Hungary , Budapest" },
{ label: "UTC + 01:00 - Denmark , Copenhagen" , value: "UTC + 01:00 - Denmark , Copenhagen" },
{ label: "UTC + 01:00 - Ireland , Dublin" , value: "UTC + 01:00 - Ireland , Dublin" },
{ label: "UTC + 01:00 - Gibraltar , Gibraltar" , value: "UTC + 01:00 - Gibraltar , Gibraltar" },
{ label: "UTC + 01:00 - Slovenia , Ljubljana" , value: "UTC + 01:00 - Slovenia , Ljubljana" },
{ label: "UTC + 01:00 - Luxembourg , Luxembourg" , value: "UTC + 01:00 - Luxembourg , Luxembourg" },
{ label: "UTC + 01:00 - Spain , Madrid" , value: "UTC + 01:00 - Spain , Madrid" },
{ label: "UTC + 01:00 - Malta , Malta" , value: "UTC + 01:00 - Malta , Malta" },
{ label: "UTC + 01:00 - Monaco , Monaco" , value: "UTC + 01:00 - Monaco , Monaco" },
{ label: "UTC + 01:00 - Norway , Oslo" , value: "UTC + 01:00 - Norway , Oslo" },
{ label: "UTC + 01:00 - France , Paris" , value: "UTC + 01:00 - France , Paris" },
{ label: "UTC + 01:00 - Montenegro , Podgorica" , value: "UTC + 01:00 - Montenegro , Podgorica" },
{ label: "UTC + 01:00 - Czech Republic , Prague" , value: "UTC + 01:00 - Czech Republic , Prague" },
{ label: "UTC + 01:00 - Italy , Rome" , value: "UTC + 01:00 - Italy , Rome" },
{ label: "UTC + 01:00 - San Marino , San_Marino" , value: "UTC + 01:00 - San Marino , San_Marino" },
{ label: "UTC + 01:00 - Bosnia and Herzegovina , Sarajevo" , value: "UTC + 01:00 - Bosnia and Herzegovina , Sarajevo" },
{ label: "UTC + 01:00 - Macedonia , Skopje" , value: "UTC + 01:00 - Macedonia , Skopje" },
{ label: "UTC + 01:00 - Sweden , Stockholm" , value: "UTC + 01:00 - Sweden , Stockholm" },
{ label: "UTC + 01:00 - Albania , Tirane" , value: "UTC + 01:00 - Albania , Tirane" },
{ label: "UTC + 01:00 - Liechtenstein , Vaduz" , value: "UTC + 01:00 - Liechtenstein , Vaduz" },
{ label: "UTC + 01:00 - Vatican , Vatican" , value: "UTC + 01:00 - Vatican , Vatican" },
{ label: "UTC + 01:00 - Austria , Vienna" , value: "UTC + 01:00 - Austria , Vienna" },
{ label: "UTC + 01:00 - Poland , Warsaw" , value: "UTC + 01:00 - Poland , Warsaw" },
{ label: "UTC + 01:00 - Croatia , Zagreb" , value: "UTC + 01:00 - Croatia , Zagreb" },
{ label: "UTC + 01:00 - Switzerland , Zurich" , value: "UTC + 01:00 - Switzerland , Zurich" },
{ label: "UTC + 02:00 - Malawi , Blantyre" , value: "UTC + 02:00 - Malawi , Blantyre" },
{ label: "UTC + 02:00 - Burundi , Bujumbura" , value: "UTC + 02:00 - Burundi , Bujumbura" },
{ label: "UTC + 02:00 - Egypt , Cairo" , value: "UTC + 02:00 - Egypt , Cairo" },
{ label: "UTC + 02:00 - Botswana , Gaborone" , value: "UTC + 02:00 - Botswana , Gaborone" },
{ label: "UTC + 02:00 - Zimbabwe , Harare" , value: "UTC + 02:00 - Zimbabwe , Harare" },
{ label: "UTC + 02:00 - South Africa , Johannesburg" , value: "UTC + 02:00 - South Africa , Johannesburg" },
{ label: "UTC + 02:00 - Sudan , Khartoum" , value: "UTC + 02:00 - Sudan , Khartoum" },
{ label: "UTC + 02:00 - Rwanda , Kigali" , value: "UTC + 02:00 - Rwanda , Kigali" },
{ label: "UTC + 02:00 - Democratic Republic of the Congo , Lubumbashi" , value: "UTC + 02:00 - Democratic Republic of the Congo , Lubumbashi" },
{ label: "UTC + 02:00 - Zambia , Lusaka" , value: "UTC + 02:00 - Zambia , Lusaka" },
{ label: "UTC + 02:00 - Mozambique , Maputo" , value: "UTC + 02:00 - Mozambique , Maputo" },
{ label: "UTC + 02:00 - Lesotho , Maseru" , value: "UTC + 02:00 - Lesotho , Maseru" },
{ label: "UTC + 02:00 - Swaziland , Mbabane" , value: "UTC + 02:00 - Swaziland , Mbabane" },
{ label: "UTC + 02:00 - Libya , Tripoli" , value: "UTC + 02:00 - Libya , Tripoli" },
{ label: "UTC + 02:00 - Namibia , Windhoek" , value: "UTC + 02:00 - Namibia , Windhoek" },
{ label: "UTC + 02:00 - Jordan , Amman" , value: "UTC + 02:00 - Jordan , Amman" },
{ label: "UTC + 02:00 - Lebanon , Beirut" , value: "UTC + 02:00 - Lebanon , Beirut" },
{ label: "UTC + 02:00 - Syria , Damascus" , value: "UTC + 02:00 - Syria , Damascus" },
{ label: "UTC + 02:00 - Cyprus , Famagusta" , value: "UTC + 02:00 - Cyprus , Famagusta" },
{ label: "UTC + 02:00 - Palestinian Territory , Gaza" , value: "UTC + 02:00 - Palestinian Territory , Gaza" },
{ label: "UTC + 02:00 - Palestinian Territory , Hebron" , value: "UTC + 02:00 - Palestinian Territory , Hebron" },
{ label: "UTC + 02:00 - Israel , Jerusalem" , value: "UTC + 02:00 - Israel , Jerusalem" },
{ label: "UTC + 02:00 - Cyprus , Nicosia" , value: "UTC + 02:00 - Cyprus , Nicosia" },
{ label: "UTC + 02:00 - Greece , Athens" , value: "UTC + 02:00 - Greece , Athens" },
{ label: "UTC + 02:00 - Romania , Bucharest" , value: "UTC + 02:00 - Romania , Bucharest" },
{ label: "UTC + 02:00 - Moldova , Chisinau" , value: "UTC + 02:00 - Moldova , Chisinau" },
{ label: "UTC + 02:00 - Finland , Helsinki" , value: "UTC + 02:00 - Finland , Helsinki" },
{ label: "UTC + 02:00 - Russia , Kaliningrad" , value: "UTC + 02:00 - Russia , Kaliningrad" },
{ label: "UTC + 02:00 - Ukraine , Kiev" , value: "UTC + 02:00 - Ukraine , Kiev" },
{ label: "UTC + 02:00 - Aland Islands , Mariehamn" , value: "UTC + 02:00 - Aland Islands , Mariehamn" },
{ label: "UTC + 02:00 - Latvia , Riga" , value: "UTC + 02:00 - Latvia , Riga" },
{ label: "UTC + 02:00 - Bulgaria , Sofia" , value: "UTC + 02:00 - Bulgaria , Sofia" },
{ label: "UTC + 02:00 - Estonia , Tallinn" , value: "UTC + 02:00 - Estonia , Tallinn" },
{ label: "UTC + 02:00 - Ukraine , Uzhgorod" , value: "UTC + 02:00 - Ukraine , Uzhgorod" },
{ label: "UTC + 02:00 - Lithuania , Vilnius" , value: "UTC + 02:00 - Lithuania , Vilnius" },
{ label: "UTC + 02:00 - Ukraine , Zaporozhye" , value: "UTC + 02:00 - Ukraine , Zaporozhye" },
{ label: "UTC + 03:00 - Ethiopia , Addis_Ababa" , value: "UTC + 03:00 - Ethiopia , Addis_Ababa" },
{ label: "UTC + 03:00 - Eritrea , Asmara" , value: "UTC + 03:00 - Eritrea , Asmara" },
{ label: "UTC + 03:00 - Tanzania , Dar_es_Salaam" , value: "UTC + 03:00 - Tanzania , Dar_es_Salaam" },
{ label: "UTC + 03:00 - Djibouti , Djibouti" , value: "UTC + 03:00 - Djibouti , Djibouti" },
{ label: "UTC + 03:00 - South Sudan , Juba" , value: "UTC + 03:00 - South Sudan , Juba" },
{ label: "UTC + 03:00 - Uganda , Kampala" , value: "UTC + 03:00 - Uganda , Kampala" },
{ label: "UTC + 03:00 - Somalia , Mogadishu" , value: "UTC + 03:00 - Somalia , Mogadishu" },
{ label: "UTC + 03:00 - Kenya , Nairobi" , value: "UTC + 03:00 - Kenya , Nairobi" },
{ label: "UTC + 03:00 - Antarctica , Syowa" , value: "UTC + 03:00 - Antarctica , Syowa" },
{ label: "UTC + 03:00 - Yemen , Aden" , value: "UTC + 03:00 - Yemen , Aden" },
{ label: "UTC + 03:00 - Iraq , Baghdad" , value: "UTC + 03:00 - Iraq , Baghdad" },
{ label: "UTC + 03:00 - Bahrain , Bahrain" , value: "UTC + 03:00 - Bahrain , Bahrain" },
{ label: "UTC + 03:00 - Kuwait , Kuwait" , value: "UTC + 03:00 - Kuwait , Kuwait" },
{ label: "UTC + 03:00 - Qatar , Qatar" , value: "UTC + 03:00 - Qatar , Qatar" },
{ label: "UTC + 03:00 - Saudi Arabia , Riyadh" , value: "UTC + 03:00 - Saudi Arabia , Riyadh" },
{ label: "UTC + 03:00 - Turkey , Istanbul" , value: "UTC + 03:00 - Turkey , Istanbul" },
{ label: "UTC + 03:00 - Russia , Kirov" , value: "UTC + 03:00 - Russia , Kirov" },
{ label: "UTC + 03:00 - Belarus , Minsk" , value: "UTC + 03:00 - Belarus , Minsk" },
{ label: "UTC + 03:00 - Russia , Moscow" , value: "UTC + 03:00 - Russia , Moscow" },
{ label: "UTC + 03:00 - Russia , Simferopol" , value: "UTC + 03:00 - Russia , Simferopol" },
{ label: "UTC + 03:00 - Madagascar , Antananarivo" , value: "UTC + 03:00 - Madagascar , Antananarivo" },
{ label: "UTC + 03:00 - Comoros , Comoro" , value: "UTC + 03:00 - Comoros , Comoro" },
{ label: "UTC + 03:00 - Mayotte , Mayotte" , value: "UTC + 03:00 - Mayotte , Mayotte" },
{ label: "UTC + 03:30 - Iran , Tehran" , value: "UTC + 03:30 - Iran , Tehran" },
{ label: "UTC + 04:00 - Azerbaijan , Baku" , value: "UTC + 04:00 - Azerbaijan , Baku" },
{ label: "UTC + 04:00 - United Arab Emirates , Dubai" , value: "UTC + 04:00 - United Arab Emirates , Dubai" },
{ label: "UTC + 04:00 - Oman , Muscat" , value: "UTC + 04:00 - Oman , Muscat" },
{ label: "UTC + 04:00 - Georgia , Tbilisi" , value: "UTC + 04:00 - Georgia , Tbilisi" },
{ label: "UTC + 04:00 - Armenia , Yerevan" , value: "UTC + 04:00 - Armenia , Yerevan" },
{ label: "UTC + 04:00 - Russia , Astrakhan" , value: "UTC + 04:00 - Russia , Astrakhan" },
{ label: "UTC + 04:00 - Russia , Samara" , value: "UTC + 04:00 - Russia , Samara" },
{ label: "UTC + 04:00 - Russia , Saratov" , value: "UTC + 04:00 - Russia , Saratov" },
{ label: "UTC + 04:00 - Russia , Ulyanovsk" , value: "UTC + 04:00 - Russia , Ulyanovsk" },
{ label: "UTC + 04:00 - Russia , Volgograd" , value: "UTC + 04:00 - Russia , Volgograd" },
{ label: "UTC + 04:00 - Seychelles , Mahe" , value: "UTC + 04:00 - Seychelles , Mahe" },
{ label: "UTC + 04:00 - Mauritius , Mauritius" , value: "UTC + 04:00 - Mauritius , Mauritius" },
{ label: "UTC + 04:00 - Reunion , Reunion" , value: "UTC + 04:00 - Reunion , Reunion" },
{ label: "UTC + 04:30 - Afghanistan , Kabul" , value: "UTC + 04:30 - Afghanistan , Kabul" },
{ label: "UTC + 05:00 - Antarctica , Mawson" , value: "UTC + 05:00 - Antarctica , Mawson" },
{ label: "UTC + 05:00 - Kazakhstan , Aqtau" , value: "UTC + 05:00 - Kazakhstan , Aqtau" },
{ label: "UTC + 05:00 - Kazakhstan , Aqtobe" , value: "UTC + 05:00 - Kazakhstan , Aqtobe" },
{ label: "UTC + 05:00 - Turkmenistan , Ashgabat" , value: "UTC + 05:00 - Turkmenistan , Ashgabat" },
{ label: "UTC + 05:00 - Kazakhstan , Atyrau" , value: "UTC + 05:00 - Kazakhstan , Atyrau" },
{ label: "UTC + 05:00 - Tajikistan , Dushanbe" , value: "UTC + 05:00 - Tajikistan , Dushanbe" },
{ label: "UTC + 05:00 - Pakistan , Karachi" , value: "UTC + 05:00 - Pakistan , Karachi" },
{ label: "UTC + 05:00 - Kazakhstan , Oral" , value: "UTC + 05:00 - Kazakhstan , Oral" },
{ label: "UTC + 05:00 - Kazakhstan , Qyzylorda" , value: "UTC + 05:00 - Kazakhstan , Qyzylorda" },
{ label: "UTC + 05:00 - Uzbekistan , Samarkand" , value: "UTC + 05:00 - Uzbekistan , Samarkand" },
{ label: "UTC + 05:00 - Uzbekistan , Tashkent" , value: "UTC + 05:00 - Uzbekistan , Tashkent" },
{ label: "UTC + 05:00 - Russia , Yekaterinburg" , value: "UTC + 05:00 - Russia , Yekaterinburg" },
{ label: "UTC + 05:00 - French Southern Territories , Kerguelen" , value: "UTC + 05:00 - French Southern Territories , Kerguelen" },
{ label: "UTC + 05:00 - Maldives , Maldives" , value: "UTC + 05:00 - Maldives , Maldives" },
{ label: "UTC + 05:30 - Sri Lanka , Colombo" , value: "UTC + 05:30 - Sri Lanka , Colombo" },
{ label: "UTC + 05:30 - India , Kolkata" , value: "UTC + 05:30 - India , Kolkata" },
{ label: "UTC + 05:45 - Nepal , Kathmandu" , value: "UTC + 05:45 - Nepal , Kathmandu" },
{ label: "UTC + 06:00 - Antarctica , Vostok" , value: "UTC + 06:00 - Antarctica , Vostok" },
{ label: "UTC + 06:00 - Kazakhstan , Almaty" , value: "UTC + 06:00 - Kazakhstan , Almaty" },
{ label: "UTC + 06:00 - Kyrgyzstan , Bishkek" , value: "UTC + 06:00 - Kyrgyzstan , Bishkek" },
{ label: "UTC + 06:00 - Bangladesh , Dhaka" , value: "UTC + 06:00 - Bangladesh , Dhaka" },
{ label: "UTC + 06:00 - Russia , Omsk" , value: "UTC + 06:00 - Russia , Omsk" },
{ label: "UTC + 06:00 - Kazakhstan , Qostanay" , value: "UTC + 06:00 - Kazakhstan , Qostanay" },
{ label: "UTC + 06:00 - Bhutan , Thimphu" , value: "UTC + 06:00 - Bhutan , Thimphu" },
{ label: "UTC + 06:00 - China , Urumqi" , value: "UTC + 06:00 - China , Urumqi" },
{ label: "UTC + 06:00 - British Indian Ocean Territory , Chagos" , value: "UTC + 06:00 - British Indian Ocean Territory , Chagos" },
{ label: "UTC + 06:30 - Myanmar , Yangon" , value: "UTC + 06:30 - Myanmar , Yangon" },
{ label: "UTC + 06:30 - Cocos Islands , Cocos" , value: "UTC + 06:30 - Cocos Islands , Cocos" },
{ label: "UTC + 07:00 - Antarctica , Davis" , value: "UTC + 07:00 - Antarctica , Davis" },
{ label: "UTC + 07:00 - Thailand , Bangkok" , value: "UTC + 07:00 - Thailand , Bangkok" },
{ label: "UTC + 07:00 - Russia , Barnaul" , value: "UTC + 07:00 - Russia , Barnaul" },
{ label: "UTC + 07:00 - Mongolia , Hovd" , value: "UTC + 07:00 - Mongolia , Hovd" },
{ label: "UTC + 07:00 - Vietnam , Ho_Chi_Minh" , value: "UTC + 07:00 - Vietnam , Ho_Chi_Minh" },
{ label: "UTC + 07:00 - Indonesia , Jakarta" , value: "UTC + 07:00 - Indonesia , Jakarta" },
{ label: "UTC + 07:00 - Russia , Krasnoyarsk" , value: "UTC + 07:00 - Russia , Krasnoyarsk" },
{ label: "UTC + 07:00 - Russia , Novokuznetsk" , value: "UTC + 07:00 - Russia , Novokuznetsk" },
{ label: "UTC + 07:00 - Russia , Novosibirsk" , value: "UTC + 07:00 - Russia , Novosibirsk" },
{ label: "UTC + 07:00 - Cambodia , Phnom_Penh" , value: "UTC + 07:00 - Cambodia , Phnom_Penh" },
{ label: "UTC + 07:00 - Indonesia , Pontianak" , value: "UTC + 07:00 - Indonesia , Pontianak" },
{ label: "UTC + 07:00 - Russia , Tomsk" , value: "UTC + 07:00 - Russia , Tomsk" },
{ label: "UTC + 07:00 - Laos , Vientiane" , value: "UTC + 07:00 - Laos , Vientiane" },
{ label: "UTC + 07:00 - Christmas Island , Christmas" , value: "UTC + 07:00 - Christmas Island , Christmas" },
{ label: "UTC + 08:00 - Antarctica , Casey" , value: "UTC + 08:00 - Antarctica , Casey" },
{ label: "UTC + 08:00 - Brunei , Brunei" , value: "UTC + 08:00 - Brunei , Brunei" },
{ label: "UTC + 08:00 - Mongolia , Choibalsan" , value: "UTC + 08:00 - Mongolia , Choibalsan" },
{ label: "UTC + 08:00 - Hong Kong , Hong_Kong" , value: "UTC + 08:00 - Hong Kong , Hong_Kong" },
{ label: "UTC + 08:00 - Russia , Irkutsk" , value: "UTC + 08:00 - Russia , Irkutsk" },
{ label: "UTC + 08:00 - Malaysia , Kuala_Lumpur" , value: "UTC + 08:00 - Malaysia , Kuala_Lumpur" },
{ label: "UTC + 08:00 - Malaysia , Kuching" , value: "UTC + 08:00 - Malaysia , Kuching" },
{ label: "UTC + 08:00 - Macao , Macau" , value: "UTC + 08:00 - Macao , Macau" },
{ label: "UTC + 08:00 - Indonesia , Makassar" , value: "UTC + 08:00 - Indonesia , Makassar" },
{ label: "UTC + 08:00 - Philippines , Manila" , value: "UTC + 08:00 - Philippines , Manila" },
{ label: "UTC + 08:00 - China , Shanghai" , value: "UTC + 08:00 - China , Shanghai" },
{ label: "UTC + 08:00 - Singapore , Singapore" , value: "UTC + 08:00 - Singapore , Singapore" },
{ label: "UTC + 08:00 - Taiwan , Taipei" , value: "UTC + 08:00 - Taiwan , Taipei" },
{ label: "UTC + 08:00 - Mongolia , Ulaanbaatar" , value: "UTC + 08:00 - Mongolia , Ulaanbaatar" },
{ label: "UTC + 08:00 - Australia , Perth" , value: "UTC + 08:00 - Australia , Perth" },
{ label: "UTC + 08:45 - Australia , Eucla" , value: "UTC + 08:45 - Australia , Eucla" },
{ label: "UTC + 09:00 - Russia , Chita" , value: "UTC + 09:00 - Russia , Chita" },
{ label: "UTC + 09:00 - East Timor , Dili" , value: "UTC + 09:00 - East Timor , Dili" },
{ label: "UTC + 09:00 - Indonesia , Jayapura" , value: "UTC + 09:00 - Indonesia , Jayapura" },
{ label: "UTC + 09:00 - Russia , Khandyga" , value: "UTC + 09:00 - Russia , Khandyga" },
{ label: "UTC + 09:00 - North Korea , Pyongyang" , value: "UTC + 09:00 - North Korea , Pyongyang" },
{ label: "UTC + 09:00 - South Korea , Seoul" , value: "UTC + 09:00 - South Korea , Seoul" },
{ label: "UTC + 09:00 - Japan , Tokyo" , value: "UTC + 09:00 - Japan , Tokyo" },
{ label: "UTC + 09:00 - Russia , Yakutsk" , value: "UTC + 09:00 - Russia , Yakutsk" },
{ label: "UTC + 09:00 - Palau , Palau" , value: "UTC + 09:00 - Palau , Palau" },
{ label: "UTC + 09:30 - Australia , Adelaide" , value: "UTC + 09:30 - Australia , Adelaide" },
{ label: "UTC + 09:30 - Australia , Broken_Hill" , value: "UTC + 09:30 - Australia , Broken_Hill" },
{ label: "UTC + 09:30 - Australia , Darwin" , value: "UTC + 09:30 - Australia , Darwin" },
{ label: "UTC + 10:00 - Antarctica , DumontDUrville" , value: "UTC + 10:00 - Antarctica , DumontDUrville" },
{ label: "UTC + 10:00 - Russia , Ust-Nera" , value: "UTC + 10:00 - Russia , Ust-Nera" },
{ label: "UTC + 10:00 - Russia , Vladivostok" , value: "UTC + 10:00 - Russia , Vladivostok" },
{ label: "UTC + 10:00 - Australia , Brisbane" , value: "UTC + 10:00 - Australia , Brisbane" },
{ label: "UTC + 10:00 - Australia , Currie" , value: "UTC + 10:00 - Australia , Currie" },
{ label: "UTC + 10:00 - Australia , Hobart" , value: "UTC + 10:00 - Australia , Hobart" },
{ label: "UTC + 10:00 - Australia , Lindeman" , value: "UTC + 10:00 - Australia , Lindeman" },
{ label: "UTC + 10:00 - Australia , Melbourne" , value: "UTC + 10:00 - Australia , Melbourne" },
{ label: "UTC + 10:00 - Australia , Sydney" , value: "UTC + 10:00 - Australia , Sydney" },
{ label: "UTC + 10:00 - Micronesia , Chuuk" , value: "UTC + 10:00 - Micronesia , Chuuk" },
{ label: "UTC + 10:00 - Guam , Guam" , value: "UTC + 10:00 - Guam , Guam" },
{ label: "UTC + 10:00 - Papua New Guinea , Port_Moresby" , value: "UTC + 10:00 - Papua New Guinea , Port_Moresby" },
{ label: "UTC + 10:00 - Northern Mariana Islands , Saipan" , value: "UTC + 10:00 - Northern Mariana Islands , Saipan" },
{ label: "UTC + 10:30 - Australia , Lord_Howe" , value: "UTC + 10:30 - Australia , Lord_Howe" },
{ label: "UTC + 11:00 - Australia , Macquarie" , value: "UTC + 11:00 - Australia , Macquarie" },
{ label: "UTC + 11:00 - Russia , Magadan" , value: "UTC + 11:00 - Russia , Magadan" },
{ label: "UTC + 11:00 - Russia , Sakhalin" , value: "UTC + 11:00 - Russia , Sakhalin" },
{ label: "UTC + 11:00 - Russia , Srednekolymsk" , value: "UTC + 11:00 - Russia , Srednekolymsk" },
{ label: "UTC + 11:00 - Papua New Guinea , Bougainville" , value: "UTC + 11:00 - Papua New Guinea , Bougainville" },
{ label: "UTC + 11:00 - Vanuatu , Efate" , value: "UTC + 11:00 - Vanuatu , Efate" },
{ label: "UTC + 11:00 - Solomon Islands , Guadalcanal" , value: "UTC + 11:00 - Solomon Islands , Guadalcanal" },
{ label: "UTC + 11:00 - Micronesia , Kosrae" , value: "UTC + 11:00 - Micronesia , Kosrae" },
{ label: "UTC + 11:00 - Norfolk Island , Norfolk" , value: "UTC + 11:00 - Norfolk Island , Norfolk" },
{ label: "UTC + 11:00 - New Caledonia , Noumea" , value: "UTC + 11:00 - New Caledonia , Noumea" },
{ label: "UTC + 11:00 - Micronesia , Pohnpei" , value: "UTC + 11:00 - Micronesia , Pohnpei" },
{ label: "UTC + 12:00 - Antarctica , McMurdo" , value: "UTC + 12:00 - Antarctica , McMurdo" },
{ label: "UTC + 12:00 - Russia , Anadyr" , value: "UTC + 12:00 - Russia , Anadyr" },
{ label: "UTC + 12:00 - Russia , Kamchatka" , value: "UTC + 12:00 - Russia , Kamchatka" },
{ label: "UTC + 12:00 - New Zealand , Auckland" , value: "UTC + 12:00 - New Zealand , Auckland" },
{ label: "UTC + 12:00 - Fiji , Fiji" , value: "UTC + 12:00 - Fiji , Fiji" },
{ label: "UTC + 12:00 - Tuvalu , Funafuti" , value: "UTC + 12:00 - Tuvalu , Funafuti" },
{ label: "UTC + 12:00 - Marshall Islands , Kwajalein" , value: "UTC + 12:00 - Marshall Islands , Kwajalein" },
{ label: "UTC + 12:00 - Marshall Islands , Majuro" , value: "UTC + 12:00 - Marshall Islands , Majuro" },
{ label: "UTC + 12:00 - Nauru , Nauru" , value: "UTC + 12:00 - Nauru , Nauru" },
{ label: "UTC + 12:00 - Kiribati , Tarawa" , value: "UTC + 12:00 - Kiribati , Tarawa" },
{ label: "UTC + 12:00 - United States Minor Outlying Islands , Wake" , value: "UTC + 12:00 - United States Minor Outlying Islands , Wake" },
{ label: "UTC + 12:00 - Wallis and Futuna , Wallis" , value: "UTC + 12:00 - Wallis and Futuna , Wallis" },
{ label: "UTC + 12:45 - New Zealand , Chatham" , value: "UTC + 12:45 - New Zealand , Chatham" },
{ label: "UTC + 13:00 - Samoa , Apia" , value: "UTC + 13:00 - Samoa , Apia" },
{ label: "UTC + 13:00 - Kiribati , Enderbury" , value: "UTC + 13:00 - Kiribati , Enderbury" },
{ label: "UTC + 13:00 - Tokelau , Fakaofo" , value: "UTC + 13:00 - Tokelau , Fakaofo" },
{ label: "UTC + 13:00 - Tonga , Tongatapu" , value: "UTC + 13:00 - Tonga , Tongatapu" },
{ label: "UTC + 14:00 - Kiribati , Kiritimati" , value: "UTC + 14:00 - Kiribati , Kiritimati" }]